### ISSUE TITLE
你好大佬，拉下代码后运行，activity_list是空白的？

### ISSUE THREAD

**Issue by IceApriler** [sdwfqin/AndroidSamples#4]
疑似ListView没渲染出来，不知道为什么。
新手刚学安卓不久，请大佬解惑，谢谢了。

![image](https://user-images.githubusercontent.com/29689307/147802739-30cff187-298c-4569-83b5-07ecbb50ad9d.png)

我看日志也没报什么错。
![image](https://user-images.githubusercontent.com/29689307/147802769-34b0951e-cea0-4c33-9d12-a800304cc004.png)

**Comment by sdwfqin** [comment]
你好，是TextView，api报错了，
![image](https://user-images.githubusercontent.com/13191807/147802973-652ff7d5-b79b-499d-be45-2d762a7936a0.png)
![image](https://user-images.githubusercontent.com/13191807/147802979-73c4aafe-53ec-4e2e-bf95-8962e8471508.png)

**Comment by IceApriler** [comment]
好的大佬，貌似是拒绝请求了。https://blog.csdn.net/java558/article/details/111357872
不过我照着这个文章改了改，似乎还是不好使。

**Comment by sdwfqin** [comment]
这个文章是没问题的。检查一下是不是改错模块

**Comment by IceApriler** [comment]
好的，谢谢，我再看看

**Comment by IceApriler** [comment]
我改了改其他模块。大佬你看页面是这样吗？我预期的是一个listview。
![image](https://user-images.githubusercontent.com/29689307/147803911-378346f7-aa94-47f9-92a0-391e4498a54b.png)

**Comment by sdwfqin** [comment]
这个页面这样子是没有问题的，这个页面只有一个textview

**Comment by IceApriler** [comment]
哦对，现在是mvpseed模块，那怎么打开app模块？这个之前就有过这种疑惑。谢谢大佬。

**Comment by IceApriler** [comment]
我貌似懂了大佬，编辑器上面是可以选择的。献丑了。
